rules:
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
  import/imports-first: 2
  import/no-unresolved: 2
  import/default: 2
  import/named: 2
  import/no-named-as-default-member: 2
  import/no-mutable-exports: 2
env:
  es6: true
  node: true
  jest: true
  browser: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
plugins:
  - import
settings:
  import/resolver: 
    webpack:
      config: 'webpack.config.js'
